example:
  security-enabled: false

management:
  server:
    port: 8081

crnk:
  path-prefix: /api
  default-page-limit: 20
  security:
    enabled: ${example.security-enabled}

github:
  client:
    client-id: 68ef680c19080cac43c8
    # really don't do that when setting up a real-world application, put it into a secure vault!
    client-secret: 48c7c62ddb3f2159596534cef8003d0d596ad369
    access-token-uri: https://github.com/login/oauth/access_token
    user-authorization-uri: https://github.com/login/oauth/authorize
    client-authentication-scheme: form
  resource:
    user-info-uri: https://api.github.com/user