kind: Service
apiVersion: "v1"
metadata:
  name: {{ .Release.Name }}-example-node
  labels:
    app: example
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    release: {{ .Release.Name }}
    deployment: example-node
