apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: cord3c-example
  labels:
    app: {{ template "contour.fullname" . }}
    chart: {{ template "contour.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
  selector:
    app: envoy
  type: LoadBalancer

