contour:
  image:
    registry: projectcontour/contour
    tag: v1.3.0
    pullPolicy: IfNotPresent
  replicas: 2
  resources: {}
    # limits:
    #   cpu: "400m"
    # requests:
    #   cpu: "200m"
customResourceDefinitions:
  create: true
  cleanup: false
envoy:
  image:
    registry: docker.io/envoyproxy/envoy
    tag: v1.11.1
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #   cpu: "400m"
    # requests:
    #   cpu: "200m"
hpa:
  create: false
    # minReplicas: 2
    # maxReplicas: 15
    # targetCPUUtilizationPercentage: 70
init:
  image:
    registry: gcr.io/heptio-images/contour
    tag: v0.15.0
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #   cpu: "400m"
    # requests:
    #   cpu: "200m"
rbac:
  create: true
serviceType: LoadBalancer
service:
  ## Further config for service of type NodePort
  ## Default config with empty string "" will assign a dynamic
  ## nodePort to http and https ports
  nodePorts:
    http: ""
    https: ""

  annotations:
    # we want to have external access, by default contour chart sets up internal access only (for whatever reason)
    cloud.google.com/load-balancer-type: External
    # contour.heptio.com/max-connections: "10000"
    # contour.heptio.com/max-requests: "1024"

serviceAccounts:
  create: true


